# Generated by Django 5.0.7 on 2024-08-01 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diddle', '0003_clientprofile_freelancerprofile_skill_trainerprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diddle.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LancerProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_text', models.TextField()),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposed_deadline', models.DateField()),
                ('lancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diddle.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diddle.project')),
            ],
        ),
    ]
